name:                my-xmonad
version:             0.1.0.0
github:              "jams2/my-xmonad"
license:             BSD3
author:              "Joshua Munn"
maintainer:          "public@elysee-munn.family"
copyright:           "Joshua Munn"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jams2/my-xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- xmonad
- xmonad-contrib
- megaparsec
- X11
- containers
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-signatures

library:
  source-dirs: src

executables:
  my-xmonad-exe:
    main:                xmonad.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad
